# Hubungin ke database db_cms yang udah lu bikin di DBeaver
spring.datasource.url=jdbc:postgresql://localhost:5433/db_cms
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver supaya Java bisa konek ke Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Fitur ajaib: Otomatis bikin/update tabel di DBeaver sesuai code Java nanti
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#port
server.port=8081

app.cors.allowed-origins=http://localhost:5173,http://192.168.1.4:5173